name: deploy trigger
run-name: Deploy to ${{ github.event.inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
        - dev1
        - dev2
        - prod
        default: 'dev1'

jobs:
  deploy-app1:
    environment:
      name: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      # - name: Invoke workflow with inputs
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     workflow: test_deploy2.yml
      #     ref: ${{ github.ref}}
      #     inputs: '{ "environment": "${{ github.event.inputs.environment }}" }'
      - name: Trigger deploy
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: babinskiy
          repo: test_gha1
          github_token: ${{ secrets.GH_TOKEN }}
          workflow_file_name: test_deploy2.yml
          ref: ${{ github.ref }}
          wait_interval: 15
          client_payload: '{ "environment": "${{ github.event.inputs.environment }}" }'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
