name: deploy reusable
run-name: ${{ github.workflow}}/${{ github.event.inputs.environment }}
concurrency:
  group: deploy-${{ github.event.inputs.environment }}
  cancel-in-progress: false
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
        - dev1
        - dev2
        - prod
        default: 'dev1'

jobs:
  deploy-app1:
    uses: ./.github/workflows/test_deploy2.yml
    secrets: inherit
    environment:
      name: ${{ github.event.inputs.environment }}
