name: deploy with trigger
run-name: ${{ github.workflow}}/${{ github.event.inputs.environment }}
concurrency:
  group: deploy-${{ github.event.inputs.environment }}
  cancel-in-progress: false
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
        default: 'dev1'
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
        default: 'dev1'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: echo "Preparing for deployment"

  deploy-app1:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Deploy to ${{ github.event.inputs.environment }}
        run: echo "Deploying to ${{ github.event.inputs.environment }}"

  deploy-app2:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Deploy to ${{ github.event.inputs.environment }}
        run: echo "Deploying to ${{ github.event.inputs.environment }}"

  create-release:
    runs-on: ubuntu-latest
    needs: [deploy-app1, deploy-app2]
    steps:
      - name: Create release
        run: echo "Creating release"
