name: deploy
run-name: Deploy to ${{ github.event.inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev1
          - dev2
          - prod
        default: 'dev1'

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Some dummy step
        run: echo "Dummy step"

  deploy:
    needs: dummy
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to ${{ github.event.inputs.environment }}
        run: echo "Deploying to ${{ github.event.inputs.environment }}"
